// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnUEexuM2YXa4mpt8_wT9y8YR5JTCL2ds',
    appId: '1:689433270181:web:132a2a20208fc03e16ba4c',
    messagingSenderId: '689433270181',
    projectId: 'fruithubapp-9d730',
    authDomain: 'fruithubapp-9d730.firebaseapp.com',
    storageBucket: 'fruithubapp-9d730.appspot.com',
    measurementId: 'G-S3EP6M10HM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhBV95bfu8-QqovAo33SHNn_wM4qA3lH0',
    appId: '1:689433270181:android:8e96ecc3d9b9cc7816ba4c',
    messagingSenderId: '689433270181',
    projectId: 'fruithubapp-9d730',
    storageBucket: 'fruithubapp-9d730.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD562Q6wfj47YEwQhL5qwgCYIGBQDlvvdg',
    appId: '1:689433270181:ios:781ff6b78ea239e116ba4c',
    messagingSenderId: '689433270181',
    projectId: 'fruithubapp-9d730',
    storageBucket: 'fruithubapp-9d730.appspot.com',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD562Q6wfj47YEwQhL5qwgCYIGBQDlvvdg',
    appId: '1:689433270181:ios:a79753f89cd9eeeb16ba4c',
    messagingSenderId: '689433270181',
    projectId: 'fruithubapp-9d730',
    storageBucket: 'fruithubapp-9d730.appspot.com',
    iosBundleId: 'com.example.fruitHub.RunnerTests',
  );
}
